language: php
sudo: required
php:
- 5.6
before_script:
- phpenv config-rm xdebug.ini
- cp .env.travis .env
- mysql -e 'create database testing;'
- composer self-update
- composer install --no-interaction --prefer-source
- composer dump-autoload
script:
- php artisan migrate
- php artisan db:seed
- php artisan key:generate
- vendor/bin/phpunit
branches:
  only:
    - master