language: php

php:
  - 5.6

before_script:
  - cp .env.travis .env
  - mysql -e 'create database testing;'
  - composer self-update --no-interaction
  - composer install --no-interaction

script:
  - php artisan migrate --no-interaction
  - php artisan db:seed --no-interaction
  - vendor/bin/phpunit