sudo: required
language: php
php:
- 5.6
before_script:
- cp .env.travis .env
- mysql -e 'create database testing;'
- composer self-update
- composer install
- composer dump-autoload
script:
- php artisan migrate
- php artisan db:seed
- vendor/bin/phpunit
deploy:
  provider: heroku
  app: marz
  api_key:
    secure: aK1lcaZRNzxMomC1vzUzPRWLa4BAXPJbGEn3f1aVOdFm6NRvPDtqLqhW6tNcj8i+TI6x9Y/2AJmwgzjfYlQvxKz6KReyuSWhb7SNc9us05Yr3bVeCrLgPsZKFA3bCXarWJw7BFGKMWkqtQPs/D7Ce9pLU1Qy7c1AnJaFMEj3SxWmQZ5NvA1lbZsJmnvC/KbGnX/S9a3o/IqMFcqn8eY0sRR+rlEHPbSvp/Vi78eTZ4+l+smP3AUl5AeZwQ5qf/ekXy3sfXPjNc5ayIy7UY2F/643FlipTGEyXTFwuDdWyipoXIAcyEDFhhPlMo6XOf7ljvWjQJ9LSvewfxMR6MMCsIHsU3Je/U+fuJAVp0nTa3ZRPuv9DZaVfiwniDAgCWu9/bayRRfltPPYJvgaUiAoIyysyO/sShgdtDtnxnBt11hPP8mxCG6s9Ox7wFyodwE3ix+SGgw6LPKSirDcKmE4ipxDKydHaYr5NJbRXQpj1KFpOmOom4gNGv8GjF0Qd3GjD0mEb8rrq2Uxy5PjHtzuPTq+jxX75tDpcS3ZXmUhzpWsIZMxKiXK7vv1r+4XPFhTlGQv7lV/+Pc7ZjcTZDevbL2VW7KEqOvpIHrE8zjYsrRfusugfEBsJ8AFvAfEfArqOK2UNERnNfpVMRzj/2jH5rPyB+lUyUzr6LNfzb5jtUA=
